### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by qqaatw** [LLaVA-VL/LLaVA-Interactive-Demo#19]
As shown below:

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/22ce0e8e-582c-4098-b7b7-722f763763eb">

**Comment by mattmazzola** [comment]
Hi Allan,

Yes, the disabling of the demo was intentional.
Unfortunately, there were some compliance and security issues related to hosting of the demo, and it was decided to remove the demo rather than allocate resources and time to address them and maintain.

I had put up the removal warning on Jun 10th, but there were still some other references and links which likely caused confusion.
I have made the warning more noticeable and removed more links.
